version: "3.8"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    image: pai-fids-app:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NUXT_HOST=${NUXT_HOST}
      - NUXT_PORT=${NUXT_PORT}
      - API_URL=${API_URL}
    ports:
      - "80:8000"
    networks:
      - pai-fids-app-net

networks:
  pai-fids-app-net:
    driver: bridge
